//! Generation and maintenance of the project `.zed/tasks.json`.
//!
//! Zed's ▶ gutter runnables come from extension-bundled task templates that
//! resolve `skills` from PATH — useless (or wrong: the PHP `llm/skills` tool
//! shares the name) for users without the CLI installed. Worktree
//! `.zed/tasks.json` tasks with the same tag *replace* the bundled ones in
//! the ▶ menu, and this server process IS the correct binary — so the
//! `skills.setupTasks` command writes/merges `.zed/tasks.json` entries whose
//! `command` is the server's own executable, and startup reconciliation
//! heals the path after extension binary updates (versioned download dirs).
//!
//! Everything here is text-edit based over the JSONC source (byte-accurate
//! ranges from `jsonc-parser`): foreign entries and comments are preserved
//! verbatim; losing user content is forbidden by design.

use std::path::Path;

use jsonc_parser::ast::{Object, Value};
use jsonc_parser::common::Ranged;
use jsonc_parser::{CollectOptions, CommentCollectionStrategy, ParseOptions};

/// Workspace-relative location of the generated file (display form).
pub const TASKS_REL: &str = ".zed/tasks.json";

/// Marker comment leading a freshly generated file.
const GENERATED_COMMENT: &str =
    "// generated by skills lsp — safe to edit; entries with skills-* tags are auto-updated";

/// Tags marking a task entry as potentially ours (mirrors the extension's
/// bundled `languages/skills-json/tasks.json`).
pub const OUR_TAGS: [&str; 3] = ["skills-sync", "skills-sync-vendor", "skills-check"];

/// Entry fields the generator owns; anything else on a managed entry
/// (`hooks`, `reveal`, `hide`, …) is user data and survives a rewrite.
const MANAGED_FIELDS: [&str; 5] = ["label", "command", "args", "cwd", "tags"];

/// One generated task, mirroring a bundled template.
struct TaskSpec {
    label: &'static str,
    args: &'static [&'static str],
    tag: &'static str,
}

const TASK_SPECS: [TaskSpec; 4] = [
    TaskSpec {
        label: "skills: update",
        args: &["update"],
        tag: "skills-sync",
    },
    TaskSpec {
        label: "skills: update --dry-run",
        args: &["update", "--dry-run"],
        tag: "skills-sync",
    },
    TaskSpec {
        label: "skills: update $ZED_CUSTOM_SKILLS_PACKAGE",
        args: &["update", "$ZED_CUSTOM_SKILLS_PACKAGE"],
        tag: "skills-sync-vendor",
    },
    TaskSpec {
        label: "skills: check",
        args: &["update", "--check"],
        tag: "skills-check",
    },
];

/// Result of [`setup_tasks`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SetupOutcome {
    Created,
    Updated,
    UpToDate,
}

/// A byte-range replacement over the original text.
struct Edit {
    start: usize,
    end: usize,
    text: String,
}

fn json_str(s: &str) -> String {
    serde_json::Value::String(s.to_string()).to_string()
}

/// Render one task entry object. `indent` is the column of the opening `{`;
/// `extras` are verbatim `"name": value` property slices carried over from a
/// previous version of the entry.
fn render_entry(spec: &TaskSpec, exe: &Path, indent: usize, extras: &[&str]) -> String {
    let pad = " ".repeat(indent);
    let inner = " ".repeat(indent + 2);
    let args = spec
        .args
        .iter()
        .map(|a| json_str(a))
        .collect::<Vec<_>>()
        .join(", ");
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(&format!("{inner}\"label\": {},\n", json_str(spec.label)));
    out.push_str(&format!(
        "{inner}\"command\": {},\n",
        json_str(&exe.to_string_lossy())
    ));
    out.push_str(&format!("{inner}\"args\": [{args}],\n"));
    out.push_str(&format!("{inner}\"cwd\": \"$ZED_WORKTREE_ROOT\",\n"));
    out.push_str(&format!("{inner}\"tags\": [{}]", json_str(spec.tag)));
    for extra in extras {
        out.push_str(&format!(",\n{inner}{extra}"));
    }
    out.push_str(&format!("\n{pad}}}"));
    out
}

/// Full content of a freshly generated `.zed/tasks.json`.
pub fn fresh_file(exe: &Path) -> String {
    let entries = TASK_SPECS
        .iter()
        .map(|spec| render_entry(spec, exe, 2, &[]))
        .collect::<Vec<_>>()
        .join(",\n  ");
    format!("{GENERATED_COMMENT}\n[\n  {entries}\n]\n")
}

/// Does the entry carry one of our tags?
fn has_our_tag(obj: &Object) -> bool {
    obj.get_array("tags").is_some_and(|tags| {
        tags.elements.iter().any(|e| {
            e.as_string_lit()
                .is_some_and(|s| OUR_TAGS.contains(&s.value.as_ref()))
        })
    })
}

/// Is this `command` value one the generator owns? Either the PATH form
/// (basename `skills` / `skills.exe` — the bundled templates and the README's
/// manual override) or a previous absolute path whose file no longer exists
/// (a pruned versioned extension download).
fn command_is_ours(command: &str) -> bool {
    let path = Path::new(command);
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    if name.eq_ignore_ascii_case("skills") || name.eq_ignore_ascii_case("skills.exe") {
        return true;
    }
    path.is_absolute() && !path.exists()
}

/// Path equality tolerant to case / separator differences on Windows.
fn same_path(a: &Path, b: &Path) -> bool {
    if a == b {
        return true;
    }
    if cfg!(windows) {
        let norm = |p: &Path| p.to_string_lossy().replace('/', "\\").to_ascii_lowercase();
        norm(a) == norm(b)
    } else {
        false
    }
}

/// Does the path point into a Zed extension work dir
/// (`…/extensions/work/<extension>/…` — versioned binary downloads live
/// there and get pruned on update)?
fn is_extension_work_dir(path: &Path) -> bool {
    let comps: Vec<String> = path
        .components()
        .map(|c| c.as_os_str().to_string_lossy().to_ascii_lowercase())
        .collect();
    comps
        .windows(2)
        .any(|w| w[0] == "extensions" && w[1] == "work")
}

/// Column (byte offset from line start) of `offset` in `text`.
fn column_of(text: &str, offset: usize) -> usize {
    text[..offset]
        .bytes()
        .rev()
        .take_while(|&b| b != b'\n')
        .count()
}

/// Apply non-overlapping edits.
fn apply_edits(text: &str, mut edits: Vec<Edit>) -> String {
    edits.sort_by_key(|e| e.start);
    let mut out = String::with_capacity(text.len());
    let mut cursor = 0;
    for edit in edits {
        out.push_str(&text[cursor..edit.start]);
        out.push_str(&edit.text);
        cursor = edit.end;
    }
    out.push_str(&text[cursor..]);
    out
}

/// Merge our entries into an existing `.zed/tasks.json` text. Returns the
/// new content, or `None` when the file is already up to date. Foreign
/// entries and comments are preserved verbatim; errors are actionable
/// messages for `window/showMessage`.
pub fn merge(existing: &str, exe: &Path) -> Result<Option<String>, String> {
    let parsed = jsonc_parser::parse_to_ast(
        existing,
        &CollectOptions {
            comments: CommentCollectionStrategy::Separate,
            tokens: false,
        },
        &ParseOptions::default(),
    )
    .map_err(|e| {
        format!("cannot parse {TASKS_REL}: {e}; fix the file (or delete it) and rerun the action")
    })?;
    let comment_ranges: Vec<(usize, usize)> = parsed
        .comments
        .iter()
        .flat_map(|map| map.values())
        .flat_map(|group| group.iter())
        .map(|c| {
            let r = c.range();
            (r.start, r.end)
        })
        .collect();
    let Some(root) = parsed.value else {
        if existing.trim().is_empty() {
            return Ok(Some(fresh_file(exe)));
        }
        return Err(format!(
            "{TASKS_REL} has no top-level value (comments only?); \
             add a task array or delete the file and rerun the action"
        ));
    };
    let Value::Array(array) = &root else {
        return Err(format!(
            "{TASKS_REL} is not a task list: expected a top-level JSON array of task entries"
        ));
    };

    let mut edits: Vec<Edit> = Vec::new();
    let mut present = [false; TASK_SPECS.len()];
    for element in &array.elements {
        let Value::Object(obj) = element else {
            continue;
        };
        if !has_our_tag(obj) {
            continue;
        }
        let Some(label) = obj.get_string("label") else {
            continue;
        };
        let Some(idx) = TASK_SPECS
            .iter()
            .position(|spec| spec.label == label.value.as_ref())
        else {
            continue; // our tag, custom label — the user's task, keep it
        };
        // A matching label with one of our tags claims the slot even when
        // the command is a user override — never append a duplicate.
        present[idx] = true;
        let Some(command) = obj.get_string("command") else {
            continue;
        };
        if !command_is_ours(command.value.as_ref()) {
            continue; // user pointed it at an existing custom binary — keep
        }
        let range = obj.range();
        let extras: Vec<&str> = obj
            .properties
            .iter()
            .filter(|p| !MANAGED_FIELDS.contains(&p.name.as_str()))
            .map(|p| {
                let r = p.range();
                &existing[r.start..r.end]
            })
            .collect();
        let rendered = render_entry(
            &TASK_SPECS[idx],
            exe,
            column_of(existing, range.start),
            &extras,
        );
        if existing[range.start..range.end] == rendered {
            continue; // already current — comments inside are fine to keep
        }
        if comment_ranges
            .iter()
            .any(|&(cs, ce)| cs < range.end && ce > range.start)
        {
            return Err(format!(
                "{TASKS_REL}: the managed task entry '{}' contains comments and would lose them \
                 on rewrite; update its \"command\" manually or move the comments outside the \
                 entry and rerun the action",
                TASK_SPECS[idx].label
            ));
        }
        edits.push(Edit {
            start: range.start,
            end: range.end,
            text: rendered,
        });
    }

    let missing: Vec<&TaskSpec> = TASK_SPECS
        .iter()
        .enumerate()
        .filter(|(idx, _)| !present[*idx])
        .map(|(_, spec)| spec)
        .collect();
    if !missing.is_empty() {
        let rendered = missing
            .iter()
            .map(|spec| format!("\n  {}", render_entry(spec, exe, 2, &[])))
            .collect::<Vec<_>>()
            .join(",");
        // Insert right after the last element (before any trailing comma or
        // comment, which then trails our last inserted entry — still valid
        // JSONC), or into the empty array.
        let (pos, text) = match array.elements.last() {
            Some(last) => (last.range().end, format!(",{rendered}")),
            None => (array.range().end - 1, format!("{rendered}\n")),
        };
        edits.push(Edit {
            start: pos,
            end: pos,
            text,
        });
    }

    if edits.is_empty() {
        return Ok(None);
    }
    let merged = apply_edits(existing, edits);
    Ok((merged != existing).then_some(merged))
}

/// Create or merge `.zed/tasks.json` under `root` with entries running
/// `exe`. The filesystem wrapper around [`fresh_file`] / [`merge`].
pub fn setup_tasks(root: &Path, exe: &Path) -> Result<SetupOutcome, String> {
    let dir = root.join(".zed");
    let path = dir.join("tasks.json");
    if !path.exists() {
        std::fs::create_dir_all(&dir)
            .map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
        std::fs::write(&path, fresh_file(exe))
            .map_err(|e| format!("cannot write {}: {e}", path.display()))?;
        return Ok(SetupOutcome::Created);
    }
    let existing = std::fs::read_to_string(&path)
        .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    match merge(&existing, exe)? {
        Some(text) => {
            std::fs::write(&path, text)
                .map_err(|e| format!("cannot write {}: {e}", path.display()))?;
            Ok(SetupOutcome::Updated)
        }
        None => Ok(SetupOutcome::UpToDate),
    }
}

/// Rewrite stale `command` paths of our entries to `exe`: an entry qualifies
/// when it carries one of our tags, its command is an *absolute* path that
/// differs from `exe`, and that path is gone from disk or points into a Zed
/// extension work dir (a stale versioned download). Only the command string
/// literal is touched — comments, foreign entries and extra fields stay
/// byte-identical. Returns the rewritten text plus the rewrite count, or
/// `None` when nothing qualifies.
pub fn reconcile_text(existing: &str, exe: &Path) -> Result<Option<(String, usize)>, String> {
    let parsed = jsonc_parser::parse_to_ast(
        existing,
        &CollectOptions::default(),
        &ParseOptions::default(),
    )
    .map_err(|e| format!("cannot parse {TASKS_REL}: {e}"))?;
    let Some(Value::Array(array)) = parsed.value else {
        return Ok(None); // not a task list — leave it alone
    };
    let mut edits: Vec<Edit> = Vec::new();
    for element in &array.elements {
        let Value::Object(obj) = element else {
            continue;
        };
        if !has_our_tag(obj) {
            continue;
        }
        let Some(command) = obj.get_string("command") else {
            continue;
        };
        let path = Path::new(command.value.as_ref());
        if !path.is_absolute() || same_path(path, exe) {
            continue; // PATH-form `skills`, or already current
        }
        if !path.exists() || is_extension_work_dir(path) {
            let range = command.range();
            edits.push(Edit {
                start: range.start,
                end: range.end,
                text: json_str(&exe.to_string_lossy()),
            });
        }
    }
    if edits.is_empty() {
        return Ok(None);
    }
    let count = edits.len();
    Ok(Some((apply_edits(existing, edits), count)))
}

/// Startup reconciliation: heal stale command paths in an *existing*
/// `.zed/tasks.json` (never creates the file). Returns how many commands
/// were rewritten, or `None` when there was nothing to do.
pub fn reconcile(root: &Path, exe: &Path) -> Result<Option<usize>, String> {
    let path = root.join(".zed").join("tasks.json");
    if !path.is_file() {
        return Ok(None);
    }
    let existing = std::fs::read_to_string(&path)
        .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    match reconcile_text(&existing, exe)? {
        Some((text, count)) => {
            std::fs::write(&path, text)
                .map_err(|e| format!("cannot write {}: {e}", path.display()))?;
            Ok(Some(count))
        }
        None => Ok(None),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// A platform-stable fake binary path with spaces + backslashes.
    fn fake_exe() -> PathBuf {
        PathBuf::from(r"C:\tools dir\skills.exe")
    }

    fn parses(text: &str) -> bool {
        jsonc_parser::parse_to_ast(text, &CollectOptions::default(), &ParseOptions::default())
            .is_ok()
    }

    #[test]
    fn fresh_file_snapshot_and_backslash_escaping() {
        let content = fresh_file(&fake_exe());
        assert!(parses(&content), "{content}");
        // Windows backslashes are JSON-escaped.
        assert!(content.contains(r#""command": "C:\\tools dir\\skills.exe""#));
        insta::assert_snapshot!(content);
    }

    #[test]
    fn merge_appends_ours_preserving_foreign_entries_and_comments() {
        let existing = "// my tasks\n[\n  {\n    \"label\": \"build\",\n    \"command\": \"cargo\",\n    \"args\": [\"build\"]\n  } // keep me\n]\n";
        let merged = merge(existing, &fake_exe()).unwrap().expect("changed");
        assert!(parses(&merged), "{merged}");
        assert!(merged.contains("// my tasks"));
        assert!(merged.contains("// keep me"));
        assert!(merged.contains("\"label\": \"build\",\n    \"command\": \"cargo\""));
        for spec in &TASK_SPECS {
            assert!(merged.contains(&json_str(spec.label)), "{}", spec.label);
        }
        assert_eq!(merged.matches(r"C:\\tools dir\\skills.exe").count(), 4);
    }

    #[test]
    fn merge_replaces_path_form_and_dead_absolute_commands() {
        let tmp = tempfile::tempdir().unwrap();
        let gone = tmp.path().join("gone").join("skills-old.exe");
        let existing = format!(
            "[\n  {{\n    \"label\": \"skills: update\",\n    \"command\": \"skills\",\n    \"args\": [\"update\"],\n    \"cwd\": \"$ZED_WORKTREE_ROOT\",\n    \"tags\": [\"skills-sync\"]\n  }},\n  {{\n    \"label\": \"skills: check\",\n    \"command\": {},\n    \"args\": [\"update\", \"--check\"],\n    \"cwd\": \"$ZED_WORKTREE_ROOT\",\n    \"tags\": [\"skills-check\"]\n  }}\n]\n",
            json_str(&gone.to_string_lossy()),
        );
        let merged = merge(&existing, &fake_exe()).unwrap().expect("changed");
        assert!(parses(&merged), "{merged}");
        assert!(!merged.contains("\"command\": \"skills\""));
        assert!(!merged.contains("skills-old.exe"));
        // 2 replaced + 2 appended, no duplicates.
        assert_eq!(merged.matches(r"C:\\tools dir\\skills.exe").count(), 4);
        for spec in &TASK_SPECS {
            assert_eq!(
                merged.matches(&json_str(spec.label)).count(),
                1,
                "{}",
                spec.label
            );
        }
    }

    #[test]
    fn merge_keeps_a_user_override_with_existing_custom_binary() {
        // Our tag + our label, but the command points at a real, existing,
        // non-`skills` binary: the user's deliberate override — keep it and
        // do NOT append a duplicate with the same label.
        let tmp = tempfile::tempdir().unwrap();
        let wrapper = tmp.path().join("wrapper.cmd");
        std::fs::write(&wrapper, "echo").unwrap();
        let entry = format!(
            "{{\n    \"label\": \"skills: update\",\n    \"command\": {},\n    \"args\": [\"update\"],\n    \"cwd\": \"$ZED_WORKTREE_ROOT\",\n    \"tags\": [\"skills-sync\"]\n  }}",
            json_str(&wrapper.to_string_lossy()),
        );
        let existing = format!("[\n  {entry}\n]\n");
        let merged = merge(&existing, &fake_exe()).unwrap().expect("changed");
        assert!(parses(&merged), "{merged}");
        assert!(merged.contains(&entry), "override rewritten: {merged}");
        assert_eq!(merged.matches("\"skills: update\"").count(), 1);
        // The other three appended.
        assert_eq!(merged.matches(r"C:\\tools dir\\skills.exe").count(), 3);
    }

    #[test]
    fn merge_preserves_extra_fields_on_managed_entries() {
        let existing = "[\n  {\n    \"label\": \"skills: check\",\n    \"command\": \"skills\",\n    \"args\": [\"update\", \"--check\"],\n    \"cwd\": \"$ZED_WORKTREE_ROOT\",\n    \"tags\": [\"skills-check\"],\n    \"hooks\": [\"create_worktree\"],\n    \"reveal\": \"no_focus\"\n  }\n]\n";
        let merged = merge(existing, &fake_exe()).unwrap().expect("changed");
        assert!(parses(&merged), "{merged}");
        assert!(merged.contains("\"hooks\": [\"create_worktree\"]"));
        assert!(merged.contains("\"reveal\": \"no_focus\""));
        assert!(!merged.contains("\"command\": \"skills\""));
        // Second run is a no-op (extras re-rendered identically).
        assert_eq!(merge(&merged, &fake_exe()).unwrap(), None);
    }

    #[test]
    fn merge_refuses_to_drop_comments_inside_a_managed_entry() {
        let existing = "[\n  {\n    \"label\": \"skills: update\",\n    // important note\n    \"command\": \"skills\",\n    \"tags\": [\"skills-sync\"]\n  }\n]\n";
        let err = merge(existing, &fake_exe()).unwrap_err();
        assert!(err.contains("comments"), "{err}");
        assert!(err.contains("skills: update"), "{err}");
    }

    #[test]
    fn merge_rejects_non_array_and_unparseable_files() {
        let err = merge("{ \"label\": \"x\" }", &fake_exe()).unwrap_err();
        assert!(err.contains("array"), "{err}");
        let err = merge("[ oops", &fake_exe()).unwrap_err();
        assert!(err.contains("cannot parse"), "{err}");
        let err = merge("// only a comment\n", &fake_exe()).unwrap_err();
        assert!(err.contains("no top-level value"), "{err}");
    }

    #[test]
    fn merge_of_empty_file_yields_fresh_content() {
        assert_eq!(
            merge("  \n", &fake_exe()).unwrap(),
            Some(fresh_file(&fake_exe()))
        );
    }

    #[test]
    fn merge_is_idempotent() {
        let fresh = fresh_file(&fake_exe());
        assert_eq!(merge(&fresh, &fake_exe()).unwrap(), None);
        // Also at a non-default indentation: first pass normalizes the
        // managed entries, the second is a no-op.
        let indented = fresh.replace("\n  ", "\n    ").replace("\n}", "\n  }");
        let merged = merge(&indented, &fake_exe()).unwrap();
        if let Some(merged) = merged {
            assert_eq!(merge(&merged, &fake_exe()).unwrap(), None);
        }
    }

    /// One-entry tasks file with our tag and the given command value.
    fn tagged_entry_file(command: &str) -> String {
        format!(
            "// header\n[\n  {{\n    \"label\": \"skills: update\",\n    \"command\": {},\n    \"args\": [\"update\"],\n    \"cwd\": \"$ZED_WORKTREE_ROOT\",\n    \"tags\": [\"skills-sync\"]\n  }},\n  {{ \"label\": \"build\", \"command\": \"cargo\", \"tags\": [\"other\"] }}\n]\n",
            json_str(command),
        )
    }

    #[test]
    fn reconcile_rewrites_a_missing_absolute_path() {
        let tmp = tempfile::tempdir().unwrap();
        let exe = tmp.path().join("bin").join("skills.exe");
        std::fs::create_dir_all(exe.parent().unwrap()).unwrap();
        std::fs::write(&exe, "x").unwrap();
        let gone = tmp.path().join("gone").join("skills.exe");
        let text = tagged_entry_file(&gone.to_string_lossy());
        let (rewritten, count) = reconcile_text(&text, &exe).unwrap().expect("rewritten");
        assert_eq!(count, 1);
        assert!(parses(&rewritten), "{rewritten}");
        assert!(rewritten.contains(&json_str(&exe.to_string_lossy())));
        // Comments + the foreign entry are byte-identical.
        assert!(rewritten.contains("// header"));
        assert!(
            rewritten.contains(
                "{ \"label\": \"build\", \"command\": \"cargo\", \"tags\": [\"other\"] }"
            )
        );
    }

    #[test]
    fn reconcile_rewrites_an_existing_extension_work_dir_path() {
        let tmp = tempfile::tempdir().unwrap();
        let exe = tmp.path().join("skills.exe");
        std::fs::write(&exe, "x").unwrap();
        let stale = tmp
            .path()
            .join("extensions")
            .join("work")
            .join("ai-skills")
            .join("skills-v0.1.0")
            .join("skills.exe");
        std::fs::create_dir_all(stale.parent().unwrap()).unwrap();
        std::fs::write(&stale, "old").unwrap(); // still on disk!
        let text = tagged_entry_file(&stale.to_string_lossy());
        let (rewritten, count) = reconcile_text(&text, &exe).unwrap().expect("rewritten");
        assert_eq!(count, 1);
        assert!(!rewritten.contains("skills-v0.1.0"));
        assert!(rewritten.contains(&json_str(&exe.to_string_lossy())));
    }

    #[test]
    fn reconcile_no_ops() {
        let tmp = tempfile::tempdir().unwrap();
        let exe = tmp.path().join("skills.exe");
        std::fs::write(&exe, "x").unwrap();
        // Current path → no-op (even when the exe lives under extensions/work).
        let text = tagged_entry_file(&exe.to_string_lossy());
        assert_eq!(reconcile_text(&text, &exe).unwrap(), None);
        let work_exe = tmp
            .path()
            .join("extensions")
            .join("work")
            .join("ai-skills")
            .join("skills.exe");
        std::fs::create_dir_all(work_exe.parent().unwrap()).unwrap();
        std::fs::write(&work_exe, "x").unwrap();
        let text = tagged_entry_file(&work_exe.to_string_lossy());
        assert_eq!(reconcile_text(&text, &work_exe).unwrap(), None);
        // Bare PATH form → no-op (not path drift).
        assert_eq!(
            reconcile_text(&tagged_entry_file("skills"), &exe).unwrap(),
            None
        );
        // Foreign tag with a dead absolute path → untouched.
        let gone = tmp.path().join("gone.exe");
        let foreign = format!(
            "[\n  {{ \"label\": \"x\", \"command\": {}, \"tags\": [\"other\"] }}\n]\n",
            json_str(&gone.to_string_lossy()),
        );
        assert_eq!(reconcile_text(&foreign, &exe).unwrap(), None);
        // Non-array / unparseable → None / Err, never a rewrite.
        assert_eq!(reconcile_text("{}", &exe).unwrap(), None);
        assert!(reconcile_text("[ oops", &exe).is_err());
    }

    #[test]
    fn reconcile_never_creates_the_file() {
        let tmp = tempfile::tempdir().unwrap();
        let exe = tmp.path().join("skills.exe");
        std::fs::write(&exe, "x").unwrap();
        assert_eq!(reconcile(tmp.path(), &exe).unwrap(), None);
        assert!(!tmp.path().join(".zed").exists());
    }

    #[test]
    fn setup_tasks_creates_then_reports_up_to_date() {
        let tmp = tempfile::tempdir().unwrap();
        let exe = tmp.path().join("skills.exe");
        std::fs::write(&exe, "x").unwrap();
        assert_eq!(
            setup_tasks(tmp.path(), &exe).unwrap(),
            SetupOutcome::Created
        );
        let path = tmp.path().join(".zed").join("tasks.json");
        let first = std::fs::read_to_string(&path).unwrap();
        assert_eq!(first, fresh_file(&exe));
        assert_eq!(
            setup_tasks(tmp.path(), &exe).unwrap(),
            SetupOutcome::UpToDate
        );
        assert_eq!(std::fs::read_to_string(&path).unwrap(), first);
        // A different exe path (this one missing) gets healed by a rerun.
        let other = tmp.path().join("elsewhere").join("skills.exe");
        std::fs::create_dir_all(other.parent().unwrap()).unwrap();
        std::fs::write(&other, "y").unwrap();
        assert_eq!(
            setup_tasks(tmp.path(), &other).unwrap(),
            SetupOutcome::Updated
        );
        assert!(
            std::fs::read_to_string(&path)
                .unwrap()
                .contains(&json_str(&other.to_string_lossy()))
        );
    }
}
